#!/usr/bin/env sh
alias dot='/usr/bin/git --git-dir=$HOME/Dotfiles/ --work-tree=$HOME'

alias vi="nvim"
alias vim="nvim"
alias vimhome="cd $XDG_CONFIG_HOME/nvim"
alias vimconfig="cd ~/.config/nvim/pieces"
alias vimplug="vim $XDG_CONFIG_HOME/nvim/pieces/plugins.vim"
alias vimlint="vim $XDG_CONFIG_HOME/nvim/pieces/plugin_ale.vim"

alias hotkeys="nvim $XDG_CONFIG_HOME/sxhkd/sxhkdrc"
alias zshconfig="nvim $ZDOTDIR/.zshrc"
alias sourcezsh="source $ZDOTDIR/.zshrc"

alias aliases="nvim $ZDOTDIR/aliases"
alias tmuxconfig="nvim $XDG_CONFIG_HOME/tmux/tmux.conf"
alias alaconfig="nvim $XDG_CONFIG_HOME/alacritty/alacritty.yml"
alias starconfig="nvim $XDG_CONFIG_HOME/starship/starship.toml"

# simple
alias ls="exa"
alias ll="ls -l"
alias la="ls -a"
alias lla="ls -la"

alias grep="grep --color=auto --exclude-dir={.bzr,CVS,.git,.hg,.svn,.idea,.tox}"

# folders
alias please='sudo $(fc -ln -1)'
alias viminit="nvim ~/.config/nvim/init.vim"
alias watch="watch -n 1"
alias size="du -sh"
alias sizeall="sudo du -sh $(ls -a)"
alias space='df -h | awk "NR==1 || /\s*\/\s*$/ || /\/home/"'
alias rs="clear && printf '\e[3J'"
alias dclean="docker system prune && docker image prune -a"
alias ipa='curl ipinfo.io/ip'
alias ccat='highlight --out-format=ansi --force'
alias xclip='xclip -sel clip'
alias gateway='ip route | head -1 | awk "{print \$3}"'
alias timer="/usr/bin/time --format='%C took %e seconds'"
